coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: 75%
        threshold: 5%
        only_pulls: true
    patch:
      default:
        target: 60%
        threshold: 10%
