coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        only_pulls: true
    patch:
      default:
        target: 80%
        threshold: 10%
