package env

// Bag holds all the config envvars
type Bag struct {
	// ServerShutdownTimeout is a duration in seconds to graceful shutdown internal
	// processes when the app has initiated a shutdown.
	ServerShutdownTimeout int `envconfig:"SERVER_SHUTDOWN_TIMEOUT" default:"5"`
	// HTTPTraceHeader is a header that provides a unique per-request ID that will be
	// injected into all logs entries related to the same request. This is used to track
	// the a request trace within the underlying services
	HTTPTraceHeader string `envconfig:"TRACEPARENT_HEADER" default:"traceparent"`
	// SMTPAddr is the hostname:port config of the SMTP server the app forwards emails to
	SMTPAddr string `envconfig:"SMTP_ADDR" required:"true"`
	// LogLevel is the level of log generated by the app
	LogLevel string `envconfig:"LOG_LEVEL" default:"info"`
}
